#pragma once

#define POSITION "POSITION"
#define NORMAL "NORMAL"
#define TANGENT "TANGENT"
#define BITANGENT "BITANGENT"
#define TEXCOORD0 "TEXCOORD0"
#define TEXCOORD1 "TEXCOORD1"
#define TEXCOORD2 "TEXCOORD2"
#define TEXCOORD3 "TEXCOORD3"